# Generated by Django 4.2.3 on 2023-07-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_head',
            field=models.TextField(max_length=30),
        ),
    ]
