# Generated by Django 4.2.3 on 2023-07-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_article_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_head',
            field=models.SlugField(max_length=30),
        ),
    ]
