# Generated by Django 4.2.3 on 2023-07-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauthen', '0004_rename_satus_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
